services:
  homepage:
    container_name: ${CONTAINER_NAME}
    image: ghcr.io/gethomepage/homepage:v1.4.0
    restart: always
    networks:
      - corapanel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
      - TZ=${TIME_ZONE}
    labels:  
      createdBy: "Apps"
networks:  
  corapanel-network:  
    external: true
