services:
  freshrss:
    image: linuxserver/freshrss:1.26.3
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - corapanel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    volumes:
      - ./data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true
