services:
  beszel:
    image: henrygd/beszel:0.12.1
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - corapanel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8090
    volumes:
      - ./data/data:/beszel_data
      - ./data/socket:/beszel_socket
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true
