services:
  qinglong:
    image: whyour/qinglong:2.19.2
    container_name: ${CONTAINER_NAME}
    networks:
      - corapanel-network
    volumes:
      - ./data:/ql/data
    ports:
      - "${PANEL_APP_PORT_HTTP}:5700"
    restart: always
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true