services:
  linux-command:
    image: wcjiang/linux-command:1.21.0
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - ${PANEL_APP_PORT_HTTP}:3000
    networks:
      - corapanel-network
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true
