services:
  drawio:
    image: jgraph/drawio:28.0.7
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    networks:
      - corapanel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
      - ${PANEL_APP_PORT_HTTPS}:8443
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true
