services:
  mcsm-web:
    image:  githubyumao/mcsmanager-web:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - corapanel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:23333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/web/data:/opt/mcsmanager/web/data
      - ./data/web/logs:/opt/mcsmanager/web/logs
    labels:  
      createdBy: "Apps"
networks:  
  corapanel-network:  
    external: true
