services:
  keydb:
    image: eqalpha/keydb:${ARCH}_v6.3.4 
    restart: always
    container_name: ${CONTAINER_NAME}
    networks:
      - corapanel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:6379
    command: keydb-server /etc/keydb/keydb.conf --requirepass ${PANEL_KEYDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data
      - ./conf/keydb.conf:/etc/keydb/keydb.conf
      - ./logs:/logs
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true