services:
  onlyoffice:
    image: onlyoffice/documentserver:9.0.3.1
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - corapanel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ./data/logs:/var/log/onlyoffice
      - ./data/data:/var/www/onlyoffice/Data
      - ./data/lib:/var/lib/onlyoffice
      - ./data/db:/var/lib/postgresql
    environment:
      - JWT_SECRET=${JWT_SECRET}
    labels:  
      createdBy: "Apps"
networks:  
  corapanel-network:  
    external: true
