services:
  heimdall:
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - corapanel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
      - "${PANEL_APP_PORT_HTTPS}:443"
    volumes:
      - "./data:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    image: linuxserver/heimdall:2.7.3
    labels:
      createdBy: "Apps"

networks:
  corapanel-network:
    external: true
