services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.16
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - corapanel-network
    volumes:
      - ./data:/app/data
    ports:
      - ${PANEL_APP_PORT_HTTP}:3001
    labels:
      createdBy: "Apps"
networks:
  corapanel-network:
    external: true