name: Update App Store JSON

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'scripts/generate_appstore.py'
      - '.github/workflows/update-appstore.yml'
  workflow_dispatch:

jobs:
  update-appstore:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
      
      - name: Generate appstore.json
        run: python scripts/generate_appstore.py
      
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet appstore.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.check_changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update appstore.json'
          title: 'Update App Store JSON'
          body: |
            This PR updates the `appstore.json` file with the latest app information.
            
            - Scanned all apps in the `/apps` directory
            - Updated metadata, versions, and file information
            - Generated new timestamps
            
            Auto-generated by GitHub Actions
          branch: update-appstore-json
          delete-branch: true
          labels: |
            automated
            app-store
          assignees: ${{ github.actor }}