name: Update App Store JSON

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches:
      - main
    paths:
      - 'apps/**'
      - 'scripts/generate_appstore.py'
      - '.github/workflows/update-appstore.yml'
  workflow_dispatch:

jobs:
  update-appstore:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
      
      - name: Generate appstore.json
        run: python scripts/generate_appstore.py
      
      - name: Minify JSON
        run: |
          python -c "import json; data = json.load(open('appstore.json')); json.dump(data, open('appstore.json', 'w'), separators=(',', ':'), ensure_ascii=False)"
      
      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes detected"
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "chore: update appstore.json [skip ci]"
          git push